services:
  - type: web
    name: caffe-fullstack
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Install Node.js dependencies and build React app
      npm install
      npm run build
    startCommand: python main.py
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.5 