services:
  - type: web
    name: caffe-fullstack
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Clear npm cache and install Node.js dependencies
      npm cache clean --force
      npm install --legacy-peer-deps
      # Build React app
      npm run build
    startCommand: python main.py
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.19.0
      - key: PYTHON_VERSION
        value: 3.11.5 